---
- name: zabbix-proxy installation
  hosts: all
  become: yes

  tasks:

  - name: download package and install zabbix-release
    apt:
      deb: http://repo.zabbix.com/zabbix/5.0/debian/pool/main/z/zabbix-release/zabbix-release_5.0-1%2Bbuster_all.deb

  - name: install zabbix-proxy-sqlite3
    apt:
      name: zabbix-proxy-sqlite3
      state: latest
      update_cache: yes

  - name: search logs
    find:
      path: /var/log/zabbix/
      file_type: any
      hidden: yes
    register: fordelete

  - name: delete logs
    file:
      path: /var/log/zabbix/*
      state: absent
    with_items: "{{ fordelete.files }}"

  - name: enable zabbix-proxy autostart
    systemd:
      name: zabbix-proxy
      enabled: yes
      state: started

  - name: restart zabbix-proxy
    service:
      name: zabbix-proxy
      state: restarted
