---
- name: zabbix-proxy installation
  hosts: all
  become: yes

  tasks:

  - name: download package and install zabbix-release
    apt:
      deb: http://repo.zabbix.com/zabbix/5.0/debian/pool/main/z/zabbix-release/zabbix-release_5.0-1%2Bbuster_all.deb

  - name: install zabbix-proxy-sqlite3
    apt:
      name: zabbix-proxy-sqlite3
      state: latest
      update_cache: yes
      
  - name: configure zabbix-agent
    shell: echo "Server=zabbix.668-010.ru\nHostname={{ hostvars[inventory_hostname]['ansible_hostname'] }}\nLogFile=/var/log/zabbix/zabbix_proxy.log\nLogFileSize=0\nPidFile=/var/run/zabbix/zabbix_proxy.pid\nSocketDir=/var/run/zabbix\nDBName=/var/lib/sqlite3/zabbix.db\nDBUser=zabbix\nSNMPTrapperFile=/var/log/snmptrap/snmptrap.log\nTimeout=4\nExternalScripts=/usr/lib/zabbix/externalscripts\nFpingLocation=/usr/bin/fping\nFping6Location=/usr/bin/fping6\nLogSlowQueries=3000\nStatsAllowedIP=127.0.0.1
" >> /etc/zabbix/zabbix_proxy.conf

  - name: delete logs
    shell: rm -rf /var/log/zabbix/*

  - name: enable zabbix-proxy autostart
    systemd:
      name: zabbix-proxy
      enabled: yes
      state: started

  - name: restart zabbix-proxy
    service:
      name: zabbix-proxy
      state: restarted
